version: '3.7'

services:
  blerdeblurb-ui:
    container_name: blerdeblurb-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ENV=docker